# 排行榜插件配置文件
# 选择语言
language: zh_CN  # 可选值: en_US (English), zh_CN (简体中文) ./Ranking/language/ 可以放入其他语言包使用

# bStats 开关
bstats:
  enabled: true  # 是否启用 bStats 统计

# 更新检查器设置
update_checker:
  enabled: true   # 是否启用更新检查器
  notify_on_login: true   # 管理员登录时是否提醒更新

# 动态记分板轮换间隔（单位：分钟）
dynamic:
  rotation_interval_minutes: 5

# 排行榜开关设置
leaderboards:
  place: true   # 是否启用放置榜
  destroys: true   # 是否启用挖掘榜
  deads: true   # 是否启用死亡榜
  mobdie: true   # 是否启用击杀榜
  onlinetime: true   # 是否启用在线时长榜
  break_bedrock: true

# 数据存储方式设置
data_storage:
  method: json   # 数据存储方式，可选值: mysql (MySQL 数据库), json (JSON 文件)

  # MySQL 配置
  mysql:
    host: localhost        # 数据库地址
    port: 3306             # 数据库端口
    username: your_username  # 数据库用户名
    password: your_password  # 数据库密码
    database: ranking_database  # 数据库名称
    table_prefix: ranking_      # 表前缀，可选项

  location: /plugins/Ranking/data   # 仅在使用 json 存储方式时有效
  save_delay: 100  # 保存延迟，单位为ticks (1 tick = 50 ms)
  regular_save_interval: 1200  # 定期保存间隔，单位为ticks (1 tick = 50 ms)
