name: Ranking
authors: [ Chlna6666 ]
version: '1.1'
main: org.com.ranking.Ranking
api-version: '1.13'

commands:
  ranking:
    description: 排行榜
    usage: /ranking <子命令>
    aliases: [rk]
    permission: ''
    children:
      place:
        description: 开启和关闭排名显示
        usage: /ranking place
        permission: ''
      destroys:
        description: 开启和关闭排名显示
        usage: /ranking destroys
        permission: ''
      deads:
        description: 开启和关闭排名显示
        usage: /ranking deads
        permission: ''
      mobdie:
        description: 开启和关闭排名显示
        usage: /ranking mobdie
        permission: ''
      onlinetime:
        description: 开启和关闭排名显示
        usage: /ranking onlinetime
        permission: ''
      help:
        description: 帮助
        usage: /ranking help
        permission: ''

folia-supported: false