name: Ranking
authors: [ Chlna6666 ]
version: ${version}
main: com.chlna6666.ranking.Ranking

api-version: '1.13'
website: https://www.minebbs.com/resources/7531/
folia-supported: false
softdepend: [PlaceholderAPI]

commands:
  ranking:
    description: 排行榜
    usage: /ranking <子命令>
    aliases: [rk]
    permission: ''
    children:
      place:
        description: 开启和关闭排名显示
        usage: /ranking place
        permission: ''
      destroys:
        description: 开启和关闭排名显示
        usage: /ranking destroys
        permission: ''
      deads:
        description: 开启和关闭排名显示
        usage: /ranking deads
        permission: ''
      mobdie:
        description: 开启和关闭排名显示
        usage: /ranking mobdie
        permission: ''
      onlinetime:
        description: 开启和关闭排名显示
        usage: /ranking onlinetime
        permission: ''
      all:
        description: 输出所有排行榜的全部数据
        usage: /ranking all
        permission: ''
      my:
        description: 输出玩家自己的所有排行榜数据
        usage: /ranking my
        permission: ''
      list:
        description: 输出指定排行榜的全部数据
        usage: /ranking list
        permission: ''
      help:
        description: 帮助
        usage: /ranking help
        permission: ''