name: Ranking
version: '1.0'
main: org.com.ranking.Ranking
api-version: '1.20'

commands:
  ranking:
    description: 排行榜
    usage: /ranking <子命令>
    aliases: [rank]
    permission: ''
    children:
      place:
        description: 开启和关闭排名显示
        usage: /ranking place
        permission: ''
      destroys:
        description: 开启和关闭排名显示
        usage: /ranking destroys
        permission: ''
      deads:
        description: 开启和关闭排名显示
        usage: /ranking deads
        permission: ''
      onlinetime:
        description: 开启和关闭排名显示
        usage: /ranking onlinetime
        permission: ''