name: Gitea CI

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # 1. 检出代码
      - name: Checkout code
        uses: actions/checkout@v4

      # 2. 设置 JDK 17（自动安装并配置）
      - uses: actions/setup-java@v4
        with:
          distribution: 'zulu' # See 'Supported distributions' for available options
          java-version: '17'
          cache: 'gradle'
          cache-dependency-path: |
            *.gradle*
            gradle-wrapper.properties


      # 3. 添加 Gradle 缓存（可选但推荐）
      - name: Cache Gradle dependencies
        uses: actions/cache@v3
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            ${{ runner.os }}-gradle-

      # 5. 执行 Gradle 构建
      - name: Build with Gradle
        run: ./gradlew shadowJar

      # 6. 上传构建产物
      - name: Upload Artifact
        uses: actions/upload-artifact@v3
        with:
          name: Ranking
          path: build/libs/*.jar